version: '3'

volumes:
  pgsql-db-scripts:
  pgsql-db-data:
    driver: local
  pg-admin-data:
    driver: local


services:
    base: &base
        hostname: app
        image: fastapi-todo-app
        stdin_open: true
        tty: true
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - .:/home/python/app
        environment: &env
            ENV: "development"
            LOG_LEVEL: "debug"
            PYTHONPATH: "/home/python/app"
            DATABASE_PG_URL: "postgresql://postgres:dev1234@pgsql-db/todolist_dev"
            WEB_APP_DEBUG: "true"
            WEB_APP_DESCRIPTION: "Todolist Task Management Application"
            WEB_APP_TITLE: "Todolist"
            WEB_APP_VERSION: "0.0.1"
            WEB_SERVER_HOST: "0.0.0.0"
            WEB_SERVER_PORT: 8000
            WEB_SERVER_RELOAD: "true"

    app:
        <<: *base
        command: /bin/ash -c "poetry install && python -m uvicorn todolist:web_app --host 0.0.0.0 --reload"
        ports:
          - "8000:8000"
        depends_on:
          - pgsql-db

    lint:
        <<: *base
        command: /bin/ash -c "poetry install && python -m flake8 todolist/ tests/"
        
    static-analysis:
        <<: *base
        command: /bin/ash -c "poetry install && python -m mypy todolist/ tests/"

    tests:
        <<: *base
        command: /bin/ash -c "poetry install && python -m pytest"
        environment:
          <<: *env
          ENV: "testing"
          DATABASE_PG_URL: "postgresql://postgres:dev1234@pgsql-db/todolist_test"
        depends_on:
          - pgsql-db

    pgsql-db:
        hostname: pgsql-db
        image: postgres:12-alpine
        environment:
          POSTGRES_PASSWORD: "dev1234"
        ports:
          - "5432:5432"
        volumes:
          - ./scripts/pgsql-db:/docker-entrypoint-initdb.d
          - pgsql-db-data:/var/lib/postgresql/data

    pgadmin:
        hostname: pgadmin4
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: "dev@dev.com"
          PGADMIN_DEFAULT_PASSWORD: "dev@1234"
        ports:
          - "6001:80"
        volumes:
          - pg-admin-data:/var/lib/pgadmin
        depends_on:
          - pgsql-db

